language: cpp
os: linux
dist: trusty
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
script:
  - make travis
